spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zuul-enhance?serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

zuul:
  sensitive-headers:
  routes:
    auth:
      path: /product/**
      service-id: xmall-product
      strip-prefix: true

    admin:
      path: /admin/**
      service-id: zuuladmin
      strip-prefix: true
